// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ReRoute.Api.Data;

#nullable disable

namespace ReRoute.Api.Migrations
{
    [DbContext(typeof(ReRouteDbContext))]
    [Migration("20260615215448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReRoute.Api.Models.Doacao", b =>
                {
                    b.Property<long>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DONATIONID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DonationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("LocalRetirada")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("LOCALRETIRADA");

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOMEITEM");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PARTICIPANTID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TAMANHO");

                    b.HasKey("DonationId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ESG_DOACAO", (string)null);
                });

            modelBuilder.Entity("ReRoute.Api.Models.Entrega", b =>
                {
                    b.Property<long>("EntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ENTREGAID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EntregaId"));

                    b.Property<DateTime?>("DataAceite")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAACEITE");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAENTREGA");

                    b.Property<long?>("ParticipantId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PARTICIPANTID");

                    b.Property<long>("SolicitacaoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SOLICITACAOID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("EntregaId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("ESG_ENTREGA", (string)null);
                });

            modelBuilder.Entity("ReRoute.Api.Models.Participante", b =>
                {
                    b.Property<long>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PARTICIPANTID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ParticipantId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("SENHA");

                    b.Property<string>("TipoPerfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPOPERFIL");

                    b.HasKey("ParticipantId");

                    b.ToTable("ESG_PARTICIPANTE", (string)null);
                });

            modelBuilder.Entity("ReRoute.Api.Models.RegistroESG", b =>
                {
                    b.Property<long>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("REGISTROID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RegistroId"));

                    b.Property<decimal>("Co2Evitado")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("CO2EVITADO");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAREGISTRO");

                    b.Property<long>("DonationId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DONATIONID");

                    b.Property<decimal>("ResiduoEvitado")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("RESIDUOEVITADO");

                    b.HasKey("RegistroId");

                    b.HasIndex("DonationId")
                        .HasDatabaseName("ESG_REGISTRO_IDX");

                    b.ToTable("ESG_REGISTRO", (string)null);
                });

            modelBuilder.Entity("ReRoute.Api.Models.Solicitacao", b =>
                {
                    b.Property<long>("SolicitacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SOLICITACAOID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SolicitacaoId"));

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATASOLICITACAO");

                    b.Property<long>("DonationId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DONATIONID");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PARTICIPANTID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("SolicitacaoId");

                    b.HasIndex("DonationId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ESG_SOLICITACAO", (string)null);
                });

            modelBuilder.Entity("ReRoute.Api.Models.Doacao", b =>
                {
                    b.HasOne("ReRoute.Api.Models.Participante", "Participante")
                        .WithMany("Doacoes")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("ReRoute.Api.Models.Entrega", b =>
                {
                    b.HasOne("ReRoute.Api.Models.Participante", "Participante")
                        .WithMany("Entregas")
                        .HasForeignKey("ParticipantId");

                    b.HasOne("ReRoute.Api.Models.Solicitacao", "Solicitacao")
                        .WithMany("Entregas")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("ReRoute.Api.Models.RegistroESG", b =>
                {
                    b.HasOne("ReRoute.Api.Models.Doacao", "Doacao")
                        .WithMany("RegistrosESG")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doacao");
                });

            modelBuilder.Entity("ReRoute.Api.Models.Solicitacao", b =>
                {
                    b.HasOne("ReRoute.Api.Models.Doacao", "Doacao")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReRoute.Api.Models.Participante", "Participante")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doacao");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("ReRoute.Api.Models.Doacao", b =>
                {
                    b.Navigation("RegistrosESG");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("ReRoute.Api.Models.Participante", b =>
                {
                    b.Navigation("Doacoes");

                    b.Navigation("Entregas");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("ReRoute.Api.Models.Solicitacao", b =>
                {
                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
